### ISSUE TITLE
Required file structure

### ISSUE THREAD

**Issue by scotiow** [ClimateCompatibleGrowth/Geo-X-data-prep#2]
It would be helpful to have the required file structure part of the repository that is downloaded (e.g. the Inputs_GeoH2/Data folder where the final hex file gets saved to avoid an error if the user doesn't create it.

Or, include in the code something along the lines of:
```
output_path = os.path.normpath("Inputs_GeoH2/Data")
if not os.path.exists(output_path):
        os.makedirs(output_path)
```

**Comment by alycialeonard** [comment]
Good catch, had forgotten to add these lines of code - will fix now and push to main!

**Comment by alycialeonard** [comment]
Empty directories now forced to push to main branch using .gitkeep, feel free to pull the latest changes to get a version with the directories in-place!
